/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Item { 
    title?: string;
    quantity?: number;
    currency_id?: string;
    unit_price?: number;
}

