/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SandwichResponseDTO } from './sandwichResponseDTO';
import { Metadata } from './metadata';


export interface SandwichesMetadataDTO { 
    sandwiches?: Array<SandwichResponseDTO>;
    metadata?: Metadata;
}

