/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SandwichResponseDTO { 
    id?: number;
    nombre?: string;
    descripcion?: string;
    origen?: string;
    tipo?: string;
    ingredientes?: Array<string>;
    vegetariano?: boolean;
    caloriasAproximadas?: number;
    imagenUrl?: string;
    precio?: number;
    disponible?: boolean;
}

